import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import React, { useState, useEffect } from "react";
import { ethers } from "ethers";
import { Table } from "react-bootstrap";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import Link from "next/link";
import { useRouter } from "next/router";
import { FaSearch } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [blocks, setBlocks] = useState([]);
  const [accountAddress, setAccountAddress] = useState("");
  const router = useRouter();

  useEffect(() => {
    const provider = new ethers.providers.JsonRpcProvider(
      "https://polygon-mumbai.g.alchemy.com/v2/KFGiZ9X78dt4jBe16IjpjVXbhlPzuSx8"
    );
    const fetchBlocks = async () => {
      const latestBlockNumber = await provider.getBlockNumber();
      const blockPromises = [];
      for (let i = 0; i < 20; i++) {
        const blockNumber = latestBlockNumber - i;
        const blockPromise = provider.getBlock(blockNumber);
        blockPromises.push(blockPromise);
      }
      const blocks = await Promise.all(blockPromises);
      setBlocks(blocks);
    };
    fetchBlocks();
  }, []);
  console.log(blocks);

  function hanldeAccount(event) {
    event.preventDefault();
    const address = document.getElementById("accountAddress").value.trim();
    setAccountAddress(address);
    router.push(`/account?${address}`);
  }

  return (
    <>
      <Head>
        <title>Explorer: Frequency Chain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar expand="lg" variant="light" bg="light">
        <Container>
          <Navbar.Brand href="#">Frequency</Navbar.Brand>
        </Container>
      </Navbar> */}

      <div className="container">
        <div className="container">
          <div className="row">
            <div className="col-lg-12 text-center">
              <img src="logos/frecGreen.png" alt="Frequency Chain logo" />
              <h1 className="text-start">Frequency Chain Explorer</h1>
              <div>
                <form>
                  <input
                    type="text"
                    placeholder="Enter Account Addrss"
                    id="accountAddress"
                    style={{
                      width: "500px",
                      borderRadius: "8px",
                    }}
                  />
                  <Link
                    onClick={hanldeAccount}
                    href={{ pathname: "/account", query: accountAddress }}
                    style={{
                      paddingLeft: "50px",
                    }}
                  >
                    <FaSearch
                      style={{
                        height: "20px",
                        width: "20px",
                      }}
                    />
                  </Link>
                </form>
              </div>

              <h3 className="text-start">Latest 20 blocks</h3>
              <div>
                <Table striped bordered hover className="table">
                  <thead>
                    <tr>
                      <th scope="col">TxHash</th>
                      <th scope="col">Block</th>
                      <th scope="col">Timestamp</th>
                      <th scope="col">Gas Used</th>
                    </tr>
                  </thead>
                  <tbody>
                    {blocks.map((block) => (
                      <tr key={block.hash}>
                        <td>
                          {" "}
                          <Link
                            href={{
                              pathname: "/transactiondetails",
                              query: block.hash,
                            }}
                          >
                            {block.hash}
                          </Link>
                        </td>
                        <td>
                          <Link
                            href={{
                              pathname: "/blockdetails",
                              query: block.number,
                            }}
                          >
                            {block.number}
                          </Link>
                        </td>
                        <td>
                          {new Date(block.timestamp * 1000).toLocaleString()}
                        </td>
                        <td>{block.gasUsed.toString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
